id: P000428
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13616
  title: ཁྲོ་ཕུ་ལོ་ཙཱ་བ་བྱམས་པ་དཔལ་གྱི་རང་རྣམ།
  author: ''
  volumes:
    eb116529f7d3449dbcd903895308da41:
      image_group_id: I1KG13635
      title: Volume 1 of khro phu lotsa+tsha ba byams pa dpal gyi rang rnam/
      volume_number: 1
      total_pages: 158
      base_file: v001.txt
